# =============================================================================
# Copyright (c) 2022, University of Wisconsin - Madison
# Copyright (c) 2022, Simulation-Based Engineering Lab
# All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be found
# in the LICENSE file at the top level of the distribution and at
#
# =============================================================================

float64[3] position
float64[3] velocity
float64[3] acceleration

float64[3] heading
float64[3] angular_velocity

